### ISSUE TITLE
YouTube tab is sometimes frozen

### ISSUE THREAD

**Issue by cramdoulfa** [tracking-exposed/YCAI#144]
when the YouTube tab is clicked on, it sometimes shows nothing.
When cliked on it again, the recommendations appear as expected
Not sure exactly of the conditions to trigger the bug, but happens quite often.

Talking out of my 🍑 , but maybe there's a 'refresh' or 'reload' to add onClick ?

**Comment by djfm** [comment]
I don't know, it seems I can reliably reproduce the bug by clicking "YouTube" => "Hide All" => "Creator" => "YouTube"

**Comment by ascariandrea** [comment]
I think this can be resolved bu this one #139 as the intervals were not properly cleared.
