### ISSUE TITLE
[ContributionBox & Injected Page] React to changes instead of polling

### ISSUE THREAD

**Issue by djfm** [tracking-exposed/YCAI#97]
Improvement upon https://github.com/tracking-exposed/YCAI/issues/77, make the UI react instead of polling for changes.

Ideas: we should convert the queries and commands defined to use the sendAPIMessage to always pass through the background

**Comment by ascariandrea** [comment]
Should be closed by #139

**Comment by djfm** [comment]
done in https://github.com/tracking-exposed/YCAI/pull/139
